name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java (para Kotlin)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Kotlin Project
        run: echo "🔨 Compilando el proyecto..."

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Tests
        run: echo "✅ Ejecutando pruebas..."

  notify:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Notify Success
        if: success()
        run: echo "✅ Tests pasaron correctamente"

      - name: Notify Failure
        if: failure()
        run: echo "❌ Tests fallaron"
